// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApquzfvHREK1GZ7L5_Ng-bJMXdkH4P8l4',
    appId: '1:152140688225:web:c3a548a5e196c2682bb320',
    messagingSenderId: '152140688225',
    projectId: 'crud-notes-project',
    authDomain: 'crud-notes-project.firebaseapp.com',
    storageBucket: 'crud-notes-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16pi6a3P-zgjWbMjmviNCaivMWlL7DzI',
    appId: '1:152140688225:android:faa1615911c0685c2bb320',
    messagingSenderId: '152140688225',
    projectId: 'crud-notes-project',
    storageBucket: 'crud-notes-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FVy4Uy9s8dBlUOEKN1vvgyZgWnxI5X4',
    appId: '1:152140688225:ios:a432856f2b7c6e302bb320',
    messagingSenderId: '152140688225',
    projectId: 'crud-notes-project',
    storageBucket: 'crud-notes-project.appspot.com',
    iosBundleId: 'com.example.crudNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FVy4Uy9s8dBlUOEKN1vvgyZgWnxI5X4',
    appId: '1:152140688225:ios:a432856f2b7c6e302bb320',
    messagingSenderId: '152140688225',
    projectId: 'crud-notes-project',
    storageBucket: 'crud-notes-project.appspot.com',
    iosBundleId: 'com.example.crudNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApquzfvHREK1GZ7L5_Ng-bJMXdkH4P8l4',
    appId: '1:152140688225:web:1dd98bb59fe2c5392bb320',
    messagingSenderId: '152140688225',
    projectId: 'crud-notes-project',
    authDomain: 'crud-notes-project.firebaseapp.com',
    storageBucket: 'crud-notes-project.appspot.com',
  );
}
